use std::io;

/* Crate rand
   the usage document can be generated by 
   "cargo doc --open"
*/
use rand::Rng;

fn main() {
    println!("Let's start a guess game");
    let rand_number = rand::thread_rng().gen_range(1..=100);

    println!("the rand number is {rand_number}");

    println!("Please input a guess");
    let mut guess = String::new();
    io::stdin()
        .read_line(&mut guess)
        .expect("read_line fail");
    

    println!("Your guess：{guess}");
}
